---
title: "Generate local drug-level dictionary for selected drugs of relevance to Klebsiella pneumoniae report"
author: "Kat Holt"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  prettydoc::html_pretty:
    theme: cayman
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# set working directory to the location of the script
knitr::opts_knit$set(root.dir = getwd())
setwd(dirname(rstudioapi::getSourceEditorContext()$path))

# load packages
library(knitr)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(patchwork)
```

# print session info (package versions)
```{r session_info}

# print versions
sessionInfo()

```

# read refgenes data
``` {r read_data}
# read as a tibble
data <- read_delim("/Users/katholt/Library/CloudStorage/GoogleDrive-drkatholt@gmail.com/My\ Drive/AMRnet/Databases/refgenes/refgenes_270224.tsv", delim="\t")

# print the dimensions of the table for reference
dim(data)
```

# drugs to report
``` {r}
# list of drugs to appear in the report
drugs_to_report <- c("Amikacin", "Ampicillin", "Ceftriaxone", "Ciprofloxacin", "Fosfomycin", "Gentamicin", "Meropenem", "Trimethoprim")
map_to_subclass <- c("AMIKACIN", "BETA-LACTAM", "CEPHALOSPORIN", "QUINOLONE", "FOSFOMYCIN", "GENTAMICIN", "CARBAPENEM", "TRIMETHOPRIM")

write_tsv(as_tibble(drugs_to_report), file="Kleb_local_drugs_to_report.tsv")
```

# list of determinants that match these, annotate with Drug
```{r}
# data %>% mutate(Drug = case_when(grepl('*AMIKACIN*', Subclass) ~ "Amikacin")) %>%

get_dets <- function(data, drugs_to_report, map_to_subclass) {
  data_dets <- data %>% filter(grepl(paste0("*",map_to_subclass[1],"*"), Subclass)) %>% mutate(Drug=drugs_to_report[1])
  for (i in 2:length(drugs_to_report)) {
     data_dets <- data %>% filter(grepl(paste0("*",map_to_subclass[i],"*"), Subclass)) %>% mutate(Drug=drugs_to_report[i]) %>% bind_rows(data_dets)
  }
  return(data_dets)
}

dets <- get_dets(data, drugs_to_report, map_to_subclass)

# remove whitelisted for other organisms
dets <- dets %>% filter(is.na(`Whitelisted taxa`) | `Whitelisted taxa`=="Klebsiella_pneumoniae")

# check new drug column vs subclass
table(dets$Subclass,dets$Drug)

```

# write it to TSV for reference
```{r write_kleb_local_dict}

write_tsv(dets %>% select(`#Allele`,`Gene family`,`Product name`,Drug,Class,Subclass,`Pubmed reference`,`RefSeq protein`), file="Kleb_local_dict.tsv")

```
